logging:
    config: classpath:logback.xml
mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.liliangliang.core.entry,com.liliangliang.core.dto
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/pm25?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
        username: root
